#!/bin/sh

##test

## Desktop background color
xsetroot -solid '#101010' &

## keyboard repeat rate
xset r on
xset r rate 400 50

## add serbian latin , russian cyrillic keyboard layouts
setxkbmap -model pc105 -layout us,rs,ru -variant ,latinyz,srp -option grp:ctrls_toggle

#synergy 
synergys --daemon -c ~/.synergy.conf &


# vnc server
#x11vnc -display :0 -geometry=1920x1080 -forever -loop -o /home/gr4yscale/.vnc/x11vnc.log


#x0vncserver -display :0 -rfbport 5900 -passwordfile ~/.vnc/passwd -Log *:stderr:100 > ~/.vnc/x0vncserver.log &

#dropbox
#/home/gr4yscale/.dropbox-dist/dropboxd &




## org
emacs &
gcal &
simplenote &

# browsing
#chromium --class=browsing --new-window https://getpocket.com/a/queue/list/ https://feedly.com https://www.reddit.com/ https://tweetdeck.twitter.com/


# comms
gmail &
messenger &
whatsapp &

# files
spacefm &
thunar &
nicotine &
deluge &
urxvt -name ranger -e bash -c "ranger" &


# media
gpodder &
deadbeef &
# mopidy chromium app

# photo
geeqie &
